# Generated by Django 4.2.5 on 2023-09-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounteur',
            options={'verbose_name': 'Счет Евро', 'verbose_name_plural': 'Счета Евро'},
        ),
        migrations.AlterModelOptions(
            name='accountrub',
            options={'verbose_name': 'Счет Рубль', 'verbose_name_plural': 'Счета Рубли'},
        ),
        migrations.AlterModelOptions(
            name='accountsom',
            options={'verbose_name': 'Счет Сом', 'verbose_name_plural': 'Счета Сомы'},
        ),
        migrations.AlterModelOptions(
            name='accountusd',
            options={'verbose_name': 'Счет Доллар', 'verbose_name_plural': 'Счета Доллары'},
        ),
    ]
