# Generated by Django 4.2.5 on 2023-09-18 10:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountSom',
            new_name='AccountKGS',
        ),
        migrations.AlterModelOptions(
            name='accounteur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='accountkgs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='accountrub',
            options={},
        ),
        migrations.AlterModelOptions(
            name='accountusd',
            options={},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='form_currency',
            new_name='from_currency',
        ),
    ]
