# Generated by Django 4.2.5 on 2023-09-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0002_rename_accountsom_accountkgs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounteur',
            options={'verbose_name': 'Счет EUR', 'verbose_name_plural': 'Счета EUR'},
        ),
        migrations.AlterModelOptions(
            name='accountkgs',
            options={'verbose_name': 'Счет KGS', 'verbose_name_plural': 'Счета KGS'},
        ),
        migrations.AlterModelOptions(
            name='accountrub',
            options={'verbose_name': 'Счет RUB', 'verbose_name_plural': 'Счета RUB'},
        ),
        migrations.AlterModelOptions(
            name='accountusd',
            options={'verbose_name': 'Счет USD', 'verbose_name_plural': 'Счета USD'},
        ),
    ]
