# Generated by Django 4.2.5 on 2023-09-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0003_alter_accounteur_options_alter_accountkgs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounteur',
            name='code_currency',
            field=models.CharField(default='usd', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountkgs',
            name='code_currency',
            field=models.CharField(default='rub', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountrub',
            name='code_currency',
            field=models.CharField(default='eur', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountusd',
            name='code_currency',
            field=models.CharField(default='kgs', max_length=3),
            preserve_default=False,
        ),
    ]
