# Generated by Django 4.2.5 on 2023-09-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0002_alter_accounteur_options_alter_accountrub_options_and_more'),
        ('exchange_app', '0004_accounteur_code_currency_accountkgs_code_currency_and_more'),
    ]

    operations = [
    ]
