# Generated by Django 4.2.5 on 2023-09-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invest_sum',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
