# Generated by Django 4.2.5 on 2023-09-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_user_invest_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invest_sum',
        ),
    ]
